version: '3.8'
services:
  backend:
    build: ./
    container_name: xplore-promote-app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - promote-network

  database:
    image: postgres:latest
    container_name: xplore-promote-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5436:5432"
    networks:
      - promote-network
    volumes:
      - pgdata_promote:/var/lib/postgresql/data

networks:
  promote-network:
    driver: bridge

volumes:
  pgdata_promote:
